### PR TITLE
Safari support on MacOS

### PR DESCRIPTION
**Pull request by iforgotn**

### CODE REVIEW

**Comment by albertopasqualetto** [comment]
Thanks!
I'm waiting for the check on the mac.

Also it is missing the code in index.js which calls macos.js

**Comment by albertopasqualetto** [comment]
I don't have permissions to write in your fork @iknowthebrazil .

Anyway you have to add:
```javascript
function getSafariPath() {
	//For macOS only
	return macos.getSafari() || null;
}
```
and then add `getSafariPath` to exported functions, all in `index.js`.

**Comment by iforgotn** [comment]
added

**Comment by iforgotn** [comment]
@albertopasqualetto

**Comment by albertopasqualetto** [comment]
Good.

**Comment by albertopasqualetto** [comment]
I have checked on an Intel Macbook.

Thanks

Published in v1.1.5

**Pull request merged**
